# Generated by Django 5.1.1 on 2025-01-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("BORROWED", "Borrowed"),
                    ("MAINTENANCE", "Maintenance"),
                ],
                default="AVAILABLE",
                max_length=20,
            ),
        ),
    ]
